server:
  port: 8080

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  # Datasource 설정
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:hello_tdd;MODE=mysql;DATABASE_TO_UPPER=false
#    username: sa
#    password:
  datasource:
    continue-on-error: true
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:hello_tdd;MODE=mysql;DATABASE_TO_UPPER=false
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace